import { ChangeDetectionStrategy, Component } from '@angular/core';

import { of } from 'rxjs';


@Component({
  selector: 'app-activities',
  templateUrl: './activities.component.html',
  styleUrls: ['./activities.component.scss'],
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class ActivitiesComponent {

  public activities = [
    {
      'id': 360,
      'content': null,
      'subjectObjectId': 88649,
      'creatorObjectId': 1,
      'activityObjectId': 44584,
      'activityTypeId': 17,
      'state': 'active',
      'createDate': '2024-11-14T10:42:02+00:00',
      'activityType': {
        'id': 17,
        'objectClass': null,
        'name': 'Assigned account',
        'state': 'active',
        'identifier': null,
        'order': 12,
        'subjectObjectClass': null,
        'color': null,
        'icon': 'playlist_add_check',
        'type': 'crmLeadAssigned',
      },
      'concreteActivityObject': {
        'id': 44584,
        'state': 'active',
        'guid': '39a8f6ca869117b680f0860d7070c638',
        'email': 'ray+55102@firestitch.com',
        'firstName': 'Alberto',
        'lastName': 'Price',
        'name': 'Alberto Price',
        'phone': '+1 (576) 611-7364',
        'createDate': '2023-05-08T19:41:52+00:00',
        'signinDate': '2024-07-12T13:40:06+00:00',
        'activateEmailDate': null,
        'activateEmailMessage': null,
        'activateDate': null,
        'timezone': 'America/Toronto',
        'type': 'staff',
        'addressId': 44585,
        'activateEmailState': null,
        'conversationUnreadNotifyMinutes': null,
        'force2fa': true,
        'middleName': null,
        'signatureId': null,
        'licenseNumber': null,
        'meetingUrl': '',
        'availableDay': null,
        'availableTime': null,
      },
      'creatorObject': {
        'id': 1,
        'class': 'account',
        'subclass': null,
        'className': null,
        'name': 'Firestitch Administrator',
        'imageUrl': 'https://firestitch-local.s3.amazonaws.com/pub/av/tiny/812e81f0613dbbe607cb00610cee2b6c_1728900036.png',
        'modifyDate': '2024-11-14T22:19:38+00:00',
        'createDate': '2023-04-25T09:55:51+00:00',
        'state': 'active',
        'meta': {
          'firstName': 'Firestitch',
          'lastName': 'Administrator',
          'email': 'admin@admin.com',
        },
        'environmentId': null,
        'parentObjectId': null,
        'modifierAccount': null,
        'identifier': null,
        'parentIdentifierObjectId': null,
      },
      'action': 'changeObject',
      'previousActivityObjectId': 88687,
      'concretePreviousActivityObject': {
        'id': 88687,
        'state': 'active',
        'guid': 'e4fb29c6da0d8752adf1f2a0dcc458e44',
        'email': 'ray+85055@firestitch.com',
        'firstName': 'Bret',
        'lastName': 'Lesch',
        'name': 'Bret Lesch',
        'phone': null,
        'createDate': '2024-11-04T18:12:31+00:00',
        'signinDate': '2024-11-04T18:12:34+00:00',
        'activateEmailDate': null,
        'activateEmailMessage': null,
        'activateDate': null,
        'timezone': null,
        'type': 'staff',
        'addressId': 88688,
        'activateEmailState': null,
        'conversationUnreadNotifyMinutes': null,
        'force2fa': true,
        'middleName': null,
        'signatureId': null,
        'licenseNumber': null,
        'meetingUrl': null,
        'availableDay': null,
        'availableTime': null,
      },
      'activityData': null,
      'previousActivityData': null,
      'objectType': {
        'class': 'crmLead',
        'name': 'Lead',
        'color': '#02A7F0',
        'icon': 'person',
      },
    },
    {
      'id': 342,
      'content': null,
      'subjectObjectId': 88649,
      'creatorObjectId': 1,
      'activityObjectId': 88604,
      'activityTypeId': 16,
      'state': 'active',
      'createDate': '2024-11-12T15:40:44+00:00',
      'activityType': {
        'id': 16,
        'objectClass': null,
        'name': 'Status',
        'state': 'active',
        'identifier': null,
        'order': 11,
        'subjectObjectClass': null,
        'color': null,
        'icon': 'playlist_add_check',
        'type': 'crmLeadStatus',
      },
      'concreteActivityObject': {
        'id': 88604,
        'parentAttributeId': null,
        'name': 'TODO',
        'class': 'crmLeadStatus',
        'backgroundColor': '#16E3AA',
        'guid': 'r7c7f52ae4be0de0c385bba82e02bd796',
        'imageTime': null,
        'configs': null,
        'order': null,
        'state': 'active',
        'image': {
          'tiny': null,
          'small': null,
        },
      },
      'creatorObject': {
        'id': 1,
        'class': 'account',
        'subclass': null,
        'className': null,
        'name': 'Firestitch Administrator',
        'imageUrl': 'https://firestitch-local.s3.amazonaws.com/pub/av/tiny/812e81f0613dbbe607cb00610cee2b6c_1728900036.png',
        'modifyDate': '2024-11-14T22:19:38+00:00',
        'createDate': '2023-04-25T09:55:51+00:00',
        'state': 'active',
        'meta': {
          'firstName': 'Firestitch',
          'lastName': 'Administrator',
          'email': 'admin@admin.com',
        },
        'environmentId': null,
        'parentObjectId': null,
        'modifierAccount': null,
        'identifier': null,
        'parentIdentifierObjectId': null,
      },
      'action': 'changeObject',
      'previousActivityObjectId': 88605,
      'concretePreviousActivityObject': {
        'id': 88605,
        'parentAttributeId': null,
        'name': 'Something else',
        'class': 'crmLeadStatus',
        'backgroundColor': '#1E78D9',
        'guid': 'l08699e62982b351ac573bfc39390b497',
        'imageTime': null,
        'configs': null,
        'order': null,
        'state': 'active',
        'image': {
          'tiny': null,
          'small': null,
        },
      },
      'activityData': null,
      'previousActivityData': null,
      'objectType': {
        'class': 'crmLead',
        'name': 'Lead',
        'color': '#02A7F0',
        'icon': 'person',
      },
    },
    {
      'id': 341,
      'content': null,
      'subjectObjectId': 88649,
      'creatorObjectId': 1,
      'activityObjectId': 88687,
      'activityTypeId': 17,
      'state': 'active',
      'createDate': '2024-11-11T20:20:47+00:00',
      'activityType': {
        'id': 17,
        'objectClass': null,
        'name': 'Assigned account',
        'state': 'active',
        'identifier': null,
        'order': 12,
        'subjectObjectClass': null,
        'color': null,
        'icon': 'playlist_add_check',
        'type': 'crmLeadAssigned',
      },
      'concreteActivityObject': {
        'id': 88687,
        'state': 'active',
        'guid': 'e4fb29c6da0d8752adf1f2a0dcc458e44',
        'email': 'ray+85055@firestitch.com',
        'firstName': 'Bret',
        'lastName': 'Lesch',
        'name': 'Bret Lesch',
        'phone': null,
        'createDate': '2024-11-04T18:12:31+00:00',
        'signinDate': '2024-11-04T18:12:34+00:00',
        'activateEmailDate': null,
        'activateEmailMessage': null,
        'activateDate': null,
        'timezone': null,
        'type': 'staff',
        'addressId': 88688,
        'activateEmailState': null,
        'conversationUnreadNotifyMinutes': null,
        'force2fa': true,
        'middleName': null,
        'signatureId': null,
        'licenseNumber': null,
        'meetingUrl': null,
        'availableDay': null,
        'availableTime': null,
      },
      'creatorObject': {
        'id': 1,
        'class': 'account',
        'subclass': null,
        'className': null,
        'name': 'Firestitch Administrator',
        'imageUrl': 'https://firestitch-local.s3.amazonaws.com/pub/av/tiny/812e81f0613dbbe607cb00610cee2b6c_1728900036.png',
        'modifyDate': '2024-11-14T22:19:38+00:00',
        'createDate': '2023-04-25T09:55:51+00:00',
        'state': 'active',
        'meta': {
          'firstName': 'Firestitch',
          'lastName': 'Administrator',
          'email': 'admin@admin.com',
        },
        'environmentId': null,
        'parentObjectId': null,
        'modifierAccount': null,
        'identifier': null,
        'parentIdentifierObjectId': null,
      },
      'action': 'changeObject',
      'previousActivityObjectId': 44584,
      'concretePreviousActivityObject': {
        'id': 44584,
        'state': 'active',
        'guid': '39a8f6ca869117b680f0860d7070c638',
        'email': 'ray+55102@firestitch.com',
        'firstName': 'Alberto',
        'lastName': 'Price',
        'name': 'Alberto Price',
        'phone': '+1 (576) 611-7364',
        'createDate': '2023-05-08T19:41:52+00:00',
        'signinDate': '2024-07-12T13:40:06+00:00',
        'activateEmailDate': null,
        'activateEmailMessage': null,
        'activateDate': null,
        'timezone': 'America/Toronto',
        'type': 'staff',
        'addressId': 44585,
        'activateEmailState': null,
        'conversationUnreadNotifyMinutes': null,
        'force2fa': true,
        'middleName': null,
        'signatureId': null,
        'licenseNumber': null,
        'meetingUrl': '',
        'availableDay': null,
        'availableTime': null,
      },
      'activityData': null,
      'previousActivityData': null,
      'objectType': {
        'class': 'crmLead',
        'name': 'Lead',
        'color': '#02A7F0',
        'icon': 'person',
      },
    },
    {
      'id': 337,
      'content': null,
      'subjectObjectId': 88649,
      'creatorObjectId': 1,
      'activityObjectId': 88763,
      'activityTypeId': 19,
      'state': 'active',
      'createDate': '2024-11-11T15:01:55+00:00',
      'activityType': {
        'id': 19,
        'objectClass': null,
        'name': 'Log',
        'state': 'active',
        'identifier': null,
        'order': 13,
        'subjectObjectClass': null,
        'color': null,
        'icon': 'playlist_add_check',
        'type': 'crmLeadLog',
      },
      'concreteActivityObject': {
        'id': 88763,
        'objectId': 88649,
        'createAccountId': 1,
        'state': 'active',
        'createDate': '2024-11-11T15:01:55+00:00',
        'notes': '<p>asdasdads</p>',
        'date': null,
        'type': 'outgoingCall',
      },
      'creatorObject': {
        'id': 1,
        'class': 'account',
        'subclass': null,
        'className': null,
        'name': 'Firestitch Administrator',
        'imageUrl': 'https://firestitch-local.s3.amazonaws.com/pub/av/tiny/812e81f0613dbbe607cb00610cee2b6c_1728900036.png',
        'modifyDate': '2024-11-14T22:19:38+00:00',
        'createDate': '2023-04-25T09:55:51+00:00',
        'state': 'active',
        'meta': {
          'firstName': 'Firestitch',
          'lastName': 'Administrator',
          'email': 'admin@admin.com',
        },
        'environmentId': null,
        'parentObjectId': null,
        'modifierAccount': null,
        'identifier': null,
        'parentIdentifierObjectId': null,
      },
      'action': 'addObject',
      'previousActivityObjectId': null,
      'activityData': null,
      'previousActivityData': null,
      'objectType': {
        'class': 'crmLog',
        'name': 'Log',
        'color': '#8389E0',
        'icon': 'assignment_add',
      },
    },
    {
      'id': 328,
      'content': null,
      'subjectObjectId': 88649,
      'creatorObjectId': 1,
      'activityObjectId': 44584,
      'activityTypeId': 17,
      'state': 'active',
      'createDate': '2024-11-11T14:15:52+00:00',
      'activityType': {
        'id': 17,
        'objectClass': null,
        'name': 'Assigned account',
        'state': 'active',
        'identifier': null,
        'order': 12,
        'subjectObjectClass': null,
        'color': null,
        'icon': 'playlist_add_check',
        'type': 'crmLeadAssigned',
      },
      'concreteActivityObject': {
        'id': 44584,
        'state': 'active',
        'guid': '39a8f6ca869117b680f0860d7070c638',
        'email': 'ray+55102@firestitch.com',
        'firstName': 'Alberto',
        'lastName': 'Price',
        'name': 'Alberto Price',
        'phone': '+1 (576) 611-7364',
        'createDate': '2023-05-08T19:41:52+00:00',
        'signinDate': '2024-07-12T13:40:06+00:00',
        'activateEmailDate': null,
        'activateEmailMessage': null,
        'activateDate': null,
        'timezone': 'America/Toronto',
        'type': 'staff',
        'addressId': 44585,
        'activateEmailState': null,
        'conversationUnreadNotifyMinutes': null,
        'force2fa': true,
        'middleName': null,
        'signatureId': null,
        'licenseNumber': null,
        'meetingUrl': '',
        'availableDay': null,
        'availableTime': null,
      },
      'creatorObject': {
        'id': 1,
        'class': 'account',
        'subclass': null,
        'className': null,
        'name': 'Firestitch Administrator',
        'imageUrl': 'https://firestitch-local.s3.amazonaws.com/pub/av/tiny/812e81f0613dbbe607cb00610cee2b6c_1728900036.png',
        'modifyDate': '2024-11-14T22:19:38+00:00',
        'createDate': '2023-04-25T09:55:51+00:00',
        'state': 'active',
        'meta': {
          'firstName': 'Firestitch',
          'lastName': 'Administrator',
          'email': 'admin@admin.com',
        },
        'environmentId': null,
        'parentObjectId': null,
        'modifierAccount': null,
        'identifier': null,
        'parentIdentifierObjectId': null,
      },
      'action': 'changeObject',
      'previousActivityObjectId': null,
      'activityData': null,
      'previousActivityData': null,
      'objectType': {
        'class': 'crmLead',
        'name': 'Lead',
        'color': '#02A7F0',
        'icon': 'person',
      },
    },
    {
      'id': 327,
      'content': null,
      'subjectObjectId': 88649,
      'creatorObjectId': 1,
      'activityObjectId': 88605,
      'activityTypeId': 16,
      'state': 'active',
      'createDate': '2024-11-11T14:15:50+00:00',
      'activityType': {
        'id': 16,
        'objectClass': null,
        'name': 'Status',
        'state': 'active',
        'identifier': null,
        'order': 11,
        'subjectObjectClass': null,
        'color': null,
        'icon': 'playlist_add_check',
        'type': 'crmLeadStatus',
      },
      'concreteActivityObject': {
        'id': 88605,
        'parentAttributeId': null,
        'name': 'Something else',
        'class': 'crmLeadStatus',
        'backgroundColor': '#1E78D9',
        'guid': 'l08699e62982b351ac573bfc39390b497',
        'imageTime': null,
        'configs': null,
        'order': null,
        'state': 'active',
        'image': {
          'tiny': null,
          'small': null,
        },
      },
      'creatorObject': {
        'id': 1,
        'class': 'account',
        'subclass': null,
        'className': null,
        'name': 'Firestitch Administrator',
        'imageUrl': 'https://firestitch-local.s3.amazonaws.com/pub/av/tiny/812e81f0613dbbe607cb00610cee2b6c_1728900036.png',
        'modifyDate': '2024-11-14T22:19:38+00:00',
        'createDate': '2023-04-25T09:55:51+00:00',
        'state': 'active',
        'meta': {
          'firstName': 'Firestitch',
          'lastName': 'Administrator',
          'email': 'admin@admin.com',
        },
        'environmentId': null,
        'parentObjectId': null,
        'modifierAccount': null,
        'identifier': null,
        'parentIdentifierObjectId': null,
      },
      'action': 'changeObject',
      'previousActivityObjectId': null,
      'activityData': null,
      'previousActivityData': null,
      'objectType': {
        'class': 'crmLead',
        'name': 'Lead',
        'color': '#02A7F0',
        'icon': 'person',
      },
    },
  ];

  public load = () => {
    return of(this.activities);
  };

}
